swagger: "2.0"
info: {}
basePath: /api
paths:
  /controlled/:
    get:
      tags:
      - controlled
      description: get controlleds
      operationId: Controlled.Get
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/controlled.ResponseControlled'
        "500":
          description: database error
    put:
      tags:
      - controlled
      description: update controlled
      operationId: Controlled.Put
      parameters:
      - in: body
        name: body
        description: The object content
        required: true
        schema:
          $ref: '#/definitions/controlled.RequestPut'
      responses:
        "200":
          description: ""
        "400":
          description: wrong body data
        "500":
          description: database error
    post:
      tags:
      - controlled
      description: create controlled
      operationId: Controlled.Post
      parameters:
      - in: body
        name: body
        description: The object content
        required: true
        schema:
          $ref: '#/definitions/controlled.RequestPost'
      responses:
        "200":
          description: "int\t\"controlled ID\""
        "400":
          description: wrong body data
        "500":
          description: database error
  /controlled/{id}:
    get:
      tags:
      - controlled
      description: get controlled
      operationId: Controlled.Get
      parameters:
      - in: path
        name: id
        description: The controlled you want to receive
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Сontrolled'
        "400":
          description: :object is empty
        "500":
          description: database error
    delete:
      tags:
      - controlled
      description: delete controlled
      operationId: Controlled.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: ""
        "400":
          description: id is empty
        "500":
          description: database error
  /controlled/info/:
    get:
      tags:
      - controlled/info
      description: get information on all controlled
      operationId: InfoControlled.Get
      responses:
        "200":
          description: "string\t\"Info a controlleds\""
        "500":
          description: database error
  /controlled/message/{controlledid}:
    post:
      tags:
      - controlled/message
      description: message to server
      operationId: ControlledMessage.Post
      parameters:
      - in: body
        name: body
        description: The object message
        required: true
        type: string
      - in: path
        name: controlledid
        description: The your id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: "string\t\"out server msg\""
        "400":
          description: wrong body data
        "500":
          description: database error
definitions:
  controlled.RequestPost:
    title: RequestPost
    type: object
    properties:
      common_buffer:
        type: integer
        format: int64
      home_control_id:
        type: string
      host:
        type: string
      name:
        type: string
      port:
        type: string
  controlled.RequestPut:
    title: RequestPut
    type: object
    properties:
      common_buffer:
        type: integer
        format: int64
      home_control_id:
        type: string
      host:
        type: string
      id:
        type: integer
        format: int64
      name:
        type: string
      port:
        type: string
  controlled.ResponseControlled:
    title: ResponseControlled
    type: object
    properties:
      common_buffer:
        type: integer
        format: int64
      home_control_id:
        type: string
      host:
        type: string
      id:
        type: integer
        format: int64
      name:
        type: string
      port:
        type: string
  models.Сontrolled:
    title: Сontrolled
    type: object
    properties:
      common_buffer:
        type: integer
        format: int64
      home_control_id:
        type: string
      host:
        type: string
      name:
        type: string
      port:
        type: string
